#!/usr/bin/perl -w

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

use strict;

my $runningSum = 0;
my $numA = 1;
my $numB = 2;

sub fibonacci{
  my $num1 = shift;
  my $num2 = shift;
  my $nextNum = $num1 + $num2;
  if($nextNum < 4000000) {
    if($nextNum % 2 == 0) {
      $runningSum += $nextNum;
    }
    return fibonacci($num2, $nextNum);
  }

  #return [$nextNum,fibonacci($num2,$nextNum)];
}

fibonacci($numA,$numB);

if($numA % 2 == 0){
	$runningSum += $numA;
}
if($numB % 2 == 0){
	$runningSum += $numB;
}

print "$runningSum\n";
